name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install system deps (for spaCy)
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
          python -m spacy download en_core_web_sm

      - name: Run tests
        run: |
          python -m pytest -q
